### **Numpy**

#### 0-d array

In [1]:
import numpy as np

In [1]:
a = 10
print(a)
print(type(a))

10
<class 'int'>


In [ ]:
ar = np.array(a) #create  an array
print(ar)
print(type(ar))

10
<class 'numpy.ndarray'>


In [ ]:
ar.ndim #to know the dimension
ar.shape # to know the shape

()

#### 1-d array

In [11]:
a = [1,2,3,4]
ar1 = np.array(a)

In [12]:
ar1.ndim

1

In [13]:
ar1.shape

(4,)

In [9]:
s = "helllo"
np.array(s)

array('helllo', dtype='<U6')

### Functions for creating 1D array

1. np.arange()

In [15]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


2. np.linspace

In [16]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

3. np.zeros()

In [18]:
np.zeros(4,dtype ='int')

array([0, 0, 0, 0])

4. np.ones()

In [20]:
np.ones(4,dtype='int')

array([1, 1, 1, 1])

5. np.random.randint()

In [21]:
np.random.randint(1,100,10)

array([27,  9, 32, 58, 71, 53, 33, 28, 81, 97])

### How to access elements from a array 

In [23]:
a = np.array([100,120,130,190,200,14,18,26])

In [22]:
#positive indexing
a[1]

np.int64(3)

In [ ]:
a[-1] #negative indexing

np.int64(26)

In [ ]:
#BASED ON SLICING
a[0:5]

array([100, 120, 130, 190, 200])

In [26]:
a[0:5:2]

array([100, 130, 200])

In [ ]:
#ACCESSING ELEMENT USING INDEX NUMBERS
a[[0,1,5,6,4,0,0,0,0]]

array([100, 120,  14,  18, 200, 100, 100, 100, 100])

In [29]:
#ACCESSING ELEMENTS BASED ON CONDITION
a = np.array([45,46,47])

a[a>45]

array([46, 47])

### Modify the values in numpy

Add a single value in array

**syntax** : np.append(array,value)

In [31]:
a = np.array([40,41,42,43])
np.append(a,46)

array([40, 41, 42, 43, 46])