### Numpy

- core of scientific computing 
- faster -> optimised , is built on c

- scikit learn uses numpy
- scipy uses numpy
- linear algebra 
- memory efficiency

### Array
- it is  datatype
- it is a homogeneous elements can only be stored
- it is more strict , same datatype only

it is a part of numpy , array will be n-dimensional

In [2]:
import numpy as np # importing the library
array_n1  =  np.array([1,2,3,4])

In [3]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [4]:
array_n1  =  np.array([1,2,3,4],dtype= "int16") #change the datatype
array_n1  =  np.array([1,2,3,4],dtype= np.int16)

In [5]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


In [6]:
 #change the datatype
array_n2  =  np.array([1,2,3,4],dtype= np.float16)
print(type(array_n2[0]))

<class 'numpy.float16'>


np.arange

In [7]:
#np.arange
np.arange(5)
np_arange = np.arange(1,10,2)

In [8]:
print(type(np_arange))

<class 'numpy.ndarray'>


np.linespace

In [9]:
#linspace (start,stop,num = x) gives evenly  spaced numbers
np_linspace = np.linspace(0,1,10)
print(np_linspace)
print(type(np_linspace))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
<class 'numpy.ndarray'>


np.zeros


In [10]:
# 1d -> [1,2,3,4]
# 2d -> [[1,2,3],[4,5,6]]
# 3d -> [[[1,2],[1,2]],[[1,2],[1,2]]]

np_1 = np.zeros(4)
print(np_1)

[0. 0. 0. 0.]


In [11]:
np_2 = np.zeros((5,5),dtype=np.int64)
print(np_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
np_3 = np.zeros((2,5,5),dtype=np.int64)
print(np_3)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [13]:
np_3.ndim #know the dimension

3

In [14]:
np_3.shape

(2, 5, 5)

np.ones

In [15]:
np.ones((5,5),dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

np.full()

In [16]:
 #list of size 10 , all filled with a value 5
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

- 1D array ->  vector
- 2D array ->  matrix
- 3D array -> matrix3d
- greater than 3D => ndarray

Identity matrix => 2D , diagonal elements will be 1

In [17]:
#identity matrix
np.eye(3,3,1) # 1 or cols

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [18]:
np.eye(3,3,-1) # -1 for rows

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

np.empty()

In [19]:
np.empty((6,6)) #it will be empty and the showing below values are garbage value

array([[9.11506850e-312, 1.19069821e-321, 0.00000000e+000,
        0.00000000e+000, 9.10336194e-312, 1.16097020e-028],
       [1.26138597e-076, 2.54867590e-028, 5.34276853e-038,
        1.04917183e-153, 5.23081515e-143, 4.75174152e-037],
       [7.86927110e-071, 2.80065108e-032, 4.42624838e-062,
        5.83506144e-144, 3.59751658e+252, 1.46901661e+179],
       [8.37404147e+242, 4.31999013e-096, 4.82337723e+228,
        1.22148508e+165, 3.27055228e+179, 6.25407449e-091],
       [2.61987637e+180, 1.52006121e-047, 5.04621343e+180,
        1.94918963e-153, 5.02836075e-037, 2.32653894e-057],
       [1.18757562e-075, 3.89189201e-033, 1.04917752e-153,
        9.08366791e+223, 5.82381891e-144, 9.11524251e-312]])

np.random.rand(shape)

In [20]:
np.random.rand(4,3)

array([[0.09205061, 0.46243527, 0.62938469],
       [0.13765022, 0.15787322, 0.00811788],
       [0.09205025, 0.6719412 , 0.70643499],
       [0.18953006, 0.1516244 , 0.16027913]])

np.random.randint

In [21]:
np.random.randint(1,10,10)

array([3, 3, 9, 5, 6, 9, 4, 3, 1, 4], dtype=int32)

### Numpy attributes

In [22]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [23]:
#ndim 
arr.ndim # check the dimension

2

In [24]:
arr.shape # to check the shape

(2, 2)

In [25]:
arr.dtype # to check the datatype

dtype('int64')

In [26]:
arr.itemsize  # it will be in bytes || 1bytes = 8bits

8

In [27]:
arr.nbytes # gives total bytes consumed by the array

32

In [28]:
arr.T #gives the transpose of the array

array([[1, 3],
       [2, 4]])

 ### Indexing & Slicing

In [29]:
arr = np.array([10,20,30,40,50,60])
print(arr[0])
print(arr[-1])

10
60


In [30]:
print(arr[1:4])
print(arr[:3])

[20 30 40]
[10 20 30]


In [31]:
print(arr[::2]) #with step 2

[10 30 50]


In [32]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
print(mat[0,1]) # array[row no , col no]

2


In [ ]:
print(mat[1]) # if i want the entire row

[4 5 6]


In [ ]:
print(mat[:,2]) # if i want the entire coloumn

[3 6 9]


In [ ]:
print(mat[:,-1]) # if i want the entire column

[3 6 9]


In [38]:
print(mat[0:2,1:])

[[2 3]
 [5 6]]


In [43]:
mat[:2,1:]

array([[2, 3],
       [5, 6]])

In [39]:
arr_temp = np.array([1,2,3,4,4,5,6,7,8,9])

arr_temp[::-1]

array([9, 8, 7, 6, 5, 4, 4, 3, 2, 1])

In [ ]:
([[9,8,7],
  [6,5,4],
  [3,2,1]])  # print this

In [44]:
mat[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Boolean indexing

In [48]:
arr = np.array([5,10,15,20,25])

In [49]:
arr>10

array([False, False,  True,  True,  True])

In [50]:
print(arr[arr>10])

[15 20 25]


In [51]:
indx = [0,3,4]
arr[indx]

array([ 5, 20, 25])

indexing with np.where()

In [52]:
arr = np.array([10,15,20,25,30])

In [55]:
idx = np.where(arr>20)
print(idx)

(array([3, 4]),)


In [56]:
print(arr[idx])

[25 30]


Array resizing and reshapeing

In [71]:
arr = np.array([1,2,3,4,5,6])
arr.shape

(6,)

In [59]:
reshape = arr.reshape(2,3)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [64]:
# -1 means auto, give -1 to unknown value
r = arr.reshape(2,-1)

In [65]:
r.shape

(2, 3)

flatten()

In [ ]:
b = r.flatten() # n dimentional to 1d
print(b)

[1 2 3 4 5 6]


resize()
- reshape will thow error if values are insufficent
- resize will truncate or padd with zeroes

In [83]:
a = np.array([1,2,3,4])

In [84]:
a.resize((2,3))

In [85]:
print(a)

[[1 2 3]
 [4 0 0]]


In [88]:
a = np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)
