### Numpy

- core of scientific computing 
- faster -> optimised , is built on c

- scikit learn uses numpy
- scipy uses numpy
- linear algebra 
- memory efficiency

### Array
- it is  datatype
- it is a homogeneous elements can only be stored
- it is more strict , same datatype only

it is a part of numpy , array will be n-dimensional

In [2]:
import numpy as np # importing the library
array_n1  =  np.array([1,2,3,4])

In [4]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
array_n1  =  np.array([1,2,3,4],dtype= "int16") #change the datatype
array_n1  =  np.array([1,2,3,4],dtype= np.int16)

In [8]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


In [10]:
 #change the datatype
array_n2  =  np.array([1,2,3,4],dtype= np.float16)
print(type(array_n2[0]))

<class 'numpy.float16'>


np.arange

In [14]:
#np.arange
np.arange(5)
np_arange = np.arange(1,10,2)

In [15]:
print(type(np_arange))

<class 'numpy.ndarray'>


np.linespace

In [ ]:
#linspace (start,stop,num = x) gives evenly  spaced numbers
np_linspace = np.linspace(0,1,10)
print(np_linspace)
print(type(np_linspace))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
<class 'numpy.ndarray'>


np.zeros


In [21]:
# 1d -> [1,2,3,4]
# 2d -> [[1,2,3],[4,5,6]]
# 3d -> [[[1,2],[1,2]],[[1,2],[1,2]]]

np_1 = np.zeros(4)
print(np_1)

[0. 0. 0. 0.]


In [25]:
np_2 = np.zeros((5,5),dtype=np.int64)
print(np_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [28]:
np_3 = np.zeros((2,5,5),dtype=np.int64)
print(np_3)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [ ]:
np_3.ndim #know the dimension

3

In [31]:
np_3.shape

(2, 5, 5)

np.ones

In [35]:
np.ones((5,5),dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

np.full()

In [36]:
 #list of size 10 , all filled with a value 5
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

- 1D array ->  vector
- 2D array ->  matrix
- 3D array -> matrix3d
- greater than 3D => ndarray

Identity matrix => 2D , diagonal elements will be 1

In [ ]:
#identity matrix
np.eye(3,3,1) # 1 or cols

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.eye(3,3,-1) # -1 for rows

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

np.empty()

In [ ]:
np.empty((6,6)) #it will be empty and the showing below values are garbage value

array([[1.09898121e-311, 1.19069821e-321, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307, 1.16097020e-028],
       [1.26138597e-076, 3.05354695e-028, 5.04888594e-038,
        1.04917183e-153, 5.23081515e-143, 1.10871938e-047],
       [1.37984398e-071, 1.36838725e-071, 2.57752079e-056,
        8.07868482e-144, 3.59751658e+252, 1.46901661e+179],
       [8.37404147e+242, 4.31999013e-096, 4.82337723e+228,
        3.85710782e-057, 4.90464699e-062, 4.26611654e-090],
       [3.40596615e-057, 1.00592310e-070, 5.04621343e+180,
        1.94918963e-153, 1.27970811e+161, 2.32498439e-057],
       [6.70258019e+170, 2.65753108e+179, 1.04914975e-153,
        9.08366791e+223, 5.82381891e-144, 1.09707182e-311]])

np.random.rand(shape)

In [48]:
np.random.rand(4,3)

array([[0.99225169, 0.74222398, 0.60632433],
       [0.86539283, 0.25532022, 0.20187443],
       [0.60057247, 0.60735876, 0.93137231],
       [0.46243675, 0.50978376, 0.38731138]])

np.rang